### ISSUE TITLE
A few suggestions for your consideration

### ISSUE THREAD

**Issue by aberja** [made2k/SunriseFasting#24]
Thanks for sharing your fasting app.  I really like the watch integration and the ability to import and export data.

If you are interested, I have a few suggestions for your consideration:
   
1. Include a Mood / Feeling option where one can record their mood at the end of the fast.  Say on a scale of 1 - 5.  

2. Include a note section where one can write about the fast, how they are feeling, etc.
    
3. Include a progress page which could include a few sections, including:
- A graph of recent fasts.  Perhaps this could be toggled between Week, Month and Year 
- A summary of achivements: Total # of fasting days, Total fasting time, Longest fast, Shortest fast, etc.

4. Include more information on the timeline page, which can also be imported / exported.  For example: 
    Start:           2021-10-01  19:00 
    End:             2021-10-02  12:30
    Percentage: 100%
    Duration:      15.0 / 15 h
    Mood:           3
    Note:            Notes about the fast, how they are feeling etc.
    
If you have any questions, please let me know.

Richard

**Comment by made2k** [comment]
Thanks for your suggestions Richard, and I'm glad you're enjoying the app! Some of these are similar to idea's I've had to add some visibility about progress/fasts into the app. Especially getting some more info into the time line.

With the two suggestions you have (mood and notes) what kind of use would you have for these? I've used some apps in the past that have these features and never found myself using them. So I'm not sure I have a clear picture to why others enjoy adding notes or moods to their fast history. Something that would help me to build these out in a useful way would be to understand what problem they're solving. Then I could make sure they're implemented right and not just added in a way that doesn't add much value.

Let me know if that makes sense and if you've got ideas around that.

**Comment by aberja** [comment]
I currently have some health issues and I'm under a doctor's care.  Before I started using apps I would wing it when I met my doctors and they asked how I have been doing.  But I found that really wasn't accurate.  So I started tracking information in a number of different apps: fasting, weight, exercise, meditation and sleep.  I then would pull out the apps in our meetings and accurately discuss with the doctor what I was doing. However, just having numbers didn't help answer the doctor's request for additional details.  This is where notes and moods come in.  I can look at the notes and mood for every day and say...oh yeah, this happened on this day and I was feeling really anxious here, and so forth. In a nutshell, the moods and notes pulls everything together and allows me to note things that I am bound to forget or not able to record in apps.

This is also one of the reasons I really like the export feature.  Rather than having to go to the app, I can export and print out the data to share with the doctors.  It really makes my life easier.

Does that help you to further understand why I'm looking for mood and notes?

I am happy to answer any other questions you might have.

**Comment by made2k** [comment]
Thanks a ton for the detail, it really does help out a lot. I see the use case now. I think it would be good as well to include that in the export so that if you're using that data anywhere else (like sending to a doctor) they have everything available. I'll get this tagged for a future release

**Comment by aberja** [comment]
Hi Zach, I was wondering if you might have any timeline for implementing the notes enhancement?

**Comment by made2k** [comment]
No timeline, been pretty busy lately. I think the outline for this feature should be relatively simple given a design can be made for it.

Off the top of my head, this would involve adding a Mood enum and Notes string to the database object. Since these are additive I think CoreData would perform the migration automatically which makes data management easy. I think the simplest way to add these to a fast would be editing from the list of fasts on the timeline tab. Though, a mood icon could definitely be placed on the main fasting screen (with the progress circle) too.

I can get a reminder for me to take a look at this so it doesn't get lost when I get some free time.

**Comment by aberja** [comment]
Thanks Zach for the update.  I am really looking forward to the update as it will allow me to retire the fasting app I am currently using and just use SunriseFasting :)

**Comment by made2k** [comment]
I have a build I'm testing that contains notes and mood markings. I need to do a bit more testing, but this may be released in the next couple of days. 
![IMG_807C20D8BCDD-1](https://user-images.githubusercontent.com/1799888/189546068-213eb0cc-2b76-4445-83ca-2af99dae1a40.jpeg)
![IMG_971D73E01870-1](https://user-images.githubusercontent.com/1799888/189546069-2d54772a-8bab-4276-9b7b-26796d5c2735.jpeg)

**Comment by made2k** [comment]
Released as a part of version 1.2.0. Maybe in the future with iOS 16's graphing library, graphs may be possible, but for now I think it's out of scope for the time being. Will need to think over the best way to show that information.
