### ISSUE TITLE
Custom fast setting is not permanent

### ISSUE THREAD

**Issue by aberja** [made2k/SunriseFasting#27]
The custom fast setting is not permanent.  I set it for 12 hours, verify it on the app and on the watch.  Then when I go to close the fast, the fasting goal has changed back to 16 hours.

Likewise, immediately after setting the custom fast to 12 hours on the iPhone and starting a fast, everything looks fine on the iPhone and the Sunrise watch complication.  If I then open the app or the complication some time later it reverts to 16 hours. (I can actually see the complication change from 12 hours to 16 hours within a second of openning it).

Please also note that when I close a fast on the iPhone, the Sunrise complication does not show that it's completed, it just continues to show the fast is open. I have to open the complication for it to update and show that the fast is finished.

**Comment by made2k** [comment]
Thanks for the report! I was able to find why the custom duration was resetting to the default (which was 16 hours). I'll get a fix out shortly for this.
