### ISSUE TITLE
Edit start and end times with watch app

### ISSUE THREAD

**Issue by aberja** [made2k/SunriseFasting#30]
I usually use the watch app to start and end fastings.  However, if I'm off by a bit, there is no way to adjust the times in the watch app and thus I have to use the iOS app.

If it's not a lot of work, it would be nice to also have the option in the watch app to edit start and end times.

**Comment by made2k** [comment]
Closing this since the iOS app now allows for editing fasts. I think it may get too crowded editing information on the watch itself. Since a completed fast can now be updated via the app, closing this for now.
