### ISSUE TITLE
Option to track eating time instead of fasting time

### ISSUE THREAD

**Issue by quinncomendant** [made2k/SunriseFasting#37]
Feature request for your beautiful app!

I want to be able to press a button to "Start" my eating, and then "Stop" when the eating period finishes. It will track the time which I was eating, and remind me to get enough calories before the eating period ends.

I struggle to get enough calories in the day because I forget to eat. Then I panic at 6pm when it's time to start my fast and end up eating two meals at once because I skipped lunch. I need an app that reminds me, "You only have a few hours left to eat, you sure you're good?" etc.

Unless Sunrise Fasting can already do this?

**Comment by made2k** [comment]
Hey, thank you for the suggestion. It's an interesting take. I think it's outside the scope of this app as the goal for Sunrise is really just to help track a fast and let you know when you've reached your goal.

That said, I think the interesting thing about your idea here is it can be thought of as an inverse fasting tracker, or could be at least. Giving this a little bit of thought, I think an app could be built to really around tracking your eating time (and thus would also be able to determine your fasting time). But with some polish there could be features like tracking your desired calorie intake and auto starting the fast when reached, or like you mention, giving reminder notifications to fulfill your calorie budget by a certain time.

As for reminders to eat, if you follow a pretty regular schedule (such as always starting your fast at 6pm) then any reminders app could be utilized to send a reminder at points in the day to keep you on track.
