### ISSUE TITLE
Translation to Swedish?

### ISSUE THREAD

**Issue by bowtiefox** [made2k/SunriseFasting#38]
I have just started using your app and I like it, however, I miss the Swedish translation and would be happy to help you with the translation. 🇸🇪

**Comment by made2k** [comment]
Hey I appreciate the suggestion. I have not revisited this project in a bit of time, but converting some of the non-localized strings into a string file for translation wouldn't be too much effort. It's mainly the buttons and notifications now that are hard coded. I could potentially get a branch up with the files to be localized if you wanted to provide the translations? Let me know what you'd think about that as I would prefer not to use a translation service to get a poor translation.

Or if you are comfortable with it, I'd be open to looking over a pull request if you wanted to get the translations implemented yourself. Either way let me know. Thanks!

**Comment by bowtiefox** [comment]
> Hey I appreciate the suggestion. I have not revisited this project in a bit of time, but converting some of the non-localized strings into a string file for translation wouldn't be too much effort. It's mainly the buttons and notifications now that are hard coded. I could potentially get a branch up with the files to be localized if you wanted to provide the translations? Let me know what you'd think about that as I would prefer not to use a translation service to get a poor translation.
> 
> 
> 
> Or if you are comfortable with it, I'd be open to looking over a pull request if you wanted to get the translations implemented yourself. Either way let me know. Thanks!

I don't need to touch the buttons but rather translation of text in text format. What do you think would be easiest? If it's just translation, it's simple to add that language to a file and update it in the App Store.

**Comment by made2k** [comment]
The easiest thing will be to add the language to the project. That will then convert the `.strings` files in the project to have 2 versions. One for English and one for Swedish (which will default to having all the English values to start). I can get those sometime this week / weekend, and then hand it off to you to take the Swedish version and translate the English strings. Then I'll just need to build it and submit and should be updated in the store for download a short time after. I can ping you once ready and we can go from there.

**Comment by made2k** [comment]
Hey @bowtiefox I have a branch up that allows for localization updates ([link here](https://github.com/made2k/SunriseFasting/tree/swe-translation)). If you want to edit directly from that branch you can check it out and edit the `.xcstrings` files. Otherwise I've exported the localizations and you can download them here, edit the `sv.xcloc` file and upload it back for me to re-import to the project.

[Fasting Localizations.zip](https://github.com/made2k/SunriseFasting/files/13603203/Fasting.Localizations.zip)

**Comment by bowtiefox** [comment]
Hello, I have started the work on the translation in Localizable.strings and will get back to you when I'm done! :)

**Comment by bowtiefox** [comment]
Hello again, thank you for your patience, attaching the translation!
[sv.xcloc.zip](https://github.com/made2k/SunriseFasting/files/14015472/sv.xcloc.zip)

**Comment by made2k** [comment]
Hey, no problem at all. I downloaded that file and was looking to get it imported, but it appears to be empty. I just want to double check to see if that is the proper file or if maybe that was an empty one by mistake.

**Comment by bowtiefox** [comment]
> appears

I will check this tomorrow. They should not be empty 🤔

**Comment by bowtiefox** [comment]
[sv.xcloc 2.zip](https://github.com/made2k/SunriseFasting/files/14042215/sv.xcloc.2.zip)

Is this file working?

**Comment by made2k** [comment]
It doesn't appear to be. What do you see when editing it? Maybe we've got a disconnect in how we're both approaching this. I don't know if it will help, but below I have a few different screenshots for what I'm seeing when viewing the included translations. I took a look at a few different ways of viewing the file.

Here's the "missing data" when importing the zipped `sv.xcloc` file into Xcode via the "import localization" option.
<img width="1162" alt="import attempt" src="https://github.com/made2k/SunriseFasting/assets/1799888/97212f53-3ebc-4cd5-bb86-b4cc771ae76d">

Here's the file `sv.xcloc` opened in Xcode just as it is (not being imported into the project).

<img width="968" alt="raw file in xcode" src="https://github.com/made2k/SunriseFasting/assets/1799888/ba2e83c3-cd03-4f35-9741-02f75e48850f">

Finally here's a translation file open in just a text editor to view the raw XML contents. It has sections for the translation units with the source, but no translated data.

<img width="446" alt="raw text data" src="https://github.com/made2k/SunriseFasting/assets/1799888/05cbeaf0-ccd9-4f0e-9d30-a96a82d1d877">

**Comment by bowtiefox** [comment]
Hmm, very strange, could you possibly create a branch that I can upload the files to?

**Comment by made2k** [comment]
There's a branch `swe-translation` currently. You should be able to fork it and upload from there if you'd like

**Comment by bowtiefox** [comment]
I chose to fork the Sunrise Repo and uploaded the files there in the directory sv.xcloc.

https://github.com/bowtiefox/SunriseFasting/tree/swe-translation/sv.xcloc

**Comment by made2k** [comment]
Perfect. I was able to get those added in this time. I'll get a build up soon with your translations. Thank you so much for taking the time to add those!
